export const mentorsData = [
  {
    id: 2,
    name: "Jane Smith",
    title: "Career Coach",
    experience: 8,
    education: "M.A. Career Development, Columbia University",
    categories: ["Resume Building", "Interview Preparation"],
    expertise: ["Career Transitions", "Resume Enhancement", "Interview Skills"],
    ratings: 4.9,
    reviewCount: 42,
    hourlyRate: 65,
    availability: ["Mon", "Wed", "Thu"],
    languages: ["English", "French"],
    image: "https://randomuser.me/api/portraits/women/44.jpg",
    bio: "Career development specialist with a focus on helping professionals transition between industries. Jane has worked with over 500 clients from diverse backgrounds."
  },
  {
    id: 3,
    name: "Dr. Alex Brown",
    title: "Academic Advisor",
    experience: 12,
    education: "Ph.D. Education, Stanford University",
    categories: ["Education Planning", "Graduate Studies"],
    expertise: ["Academic Planning", "Research Methodology", "Scholarship Applications"],
    ratings: 4.7,
    reviewCount: 28,
    hourlyRate: 75,
    availability: ["Tue", "Wed", "Fri"],
    languages: ["English", "German"],
    image: "https://randomuser.me/api/portraits/men/22.jpg",
    bio: "Educational consultant specializing in graduate studies and research careers. Alex has guided numerous students through successful applications to top-tier universities."
  },
  {
    id: 1,
    name: "Michael Johnson",
    title: "Tech Industry Specialist",
    experience: 15,
    education: "M.S. Computer Science, MIT",
    categories: ["Technology", "Professional Development"],
    expertise: ["Tech Careers", "Skills Development", "Industry Networking"],
    ratings: 4.8,
    reviewCount: 36,
    hourlyRate: 85,
    availability: ["Mon", "Tue", "Thu", "Fri"],
    languages: ["English", "Spanish"],
    image: "https://randomuser.me/api/portraits/men/32.jpg",
    bio: "Former tech industry executive with experience at leading companies. Michael helps professionals navigate the rapidly changing technology landscape and develop relevant skills."
  },
  {
    id: 4,
    name: "Dr. Sarah Chen",
    title: "Healthcare Careers Specialist",
    experience: 10,
    education: "MD, Johns Hopkins University",
    categories: ["Healthcare Careers", "Professional Development"],
    expertise: ["Medical School Applications", "Healthcare Career Paths", "Clinical Experience"],
    ratings: 4.9,
    reviewCount: 31,
    hourlyRate: 90,
    availability: ["Wed", "Thu", "Sat"],
    languages: ["English", "Mandarin"],
    image: "https://randomuser.me/api/portraits/women/28.jpg",
    bio: "Physician turned career advisor specializing in healthcare professions. Sarah guides students and professionals through the complexities of healthcare career paths."
  },
  {
    id: 5,
    name: "Robert Martinez",
    title: "Finance Career Consultant",
    experience: 14,
    education: "MBA, Wharton School of Business",
    categories: ["Finance Careers", "Professional Development"],
    expertise: ["Investment Banking", "Financial Analysis", "Corporate Finance"],
    ratings: 4.6,
    reviewCount: 24,
    hourlyRate: 80,
    availability: ["Mon", "Wed", "Fri"],
    languages: ["English", "Portuguese"],
    image: "https://randomuser.me/api/portraits/men/42.jpg",
    bio: "Former investment banker with experience on Wall Street. Robert helps professionals enter and advance in the competitive world of finance."
  },
  {
    id: 6,
    name: "Sarah Johnson",
    title: "Financial Analyst",
    experience: 7,
    education: "M.S. Finance, London School of Economics",
    categories: ["Finance", "Investment"],
    expertise: ["Financial Modeling", "Investment Analysis", "Portfolio Management", "Excel", "Python for Finance"],
    ratings: 4.7,
    reviewCount: 88,
    hourlyRate: 70,
    availability: "Weekday Evenings",
    languages: ["English", "French"],
    image: "https://randomuser.me/api/portraits/women/3.jpg",
    bio: "Financial analyst with experience at JP Morgan and Goldman Sachs. I help individuals and small businesses make informed investment decisions and develop sound financial strategies for long-term growth.",
  },
  {
    id: 7,
    name: "Dr. James Wilson",
    title: "Healthcare Consultant",
    experience: 15,
    education: "M.D., Johns Hopkins University",
    categories: ["Healthcare", "Medicine"],
    expertise: ["Healthcare Management", "Medical Technology", "Clinical Research", "Healthcare Policy"],
    ratings: 4.9,
    reviewCount: 176,
    hourlyRate: 110,
    availability: "By Appointment",
    languages: ["English"],
    image: "https://randomuser.me/api/portraits/men/4.jpg",
    bio: "Physician turned healthcare consultant with expertise in healthcare operations and medical technology implementation. I help healthcare organizations improve patient outcomes while optimizing operational efficiency.",
  },
  {
    id: 8,
    name: "Linda Park",
    title: "Human Resources Director",
    experience: 12,
    education: "M.A. Industrial Psychology, NYU",
    categories: ["Human Resources", "Career Development"],
    expertise: ["Talent Acquisition", "Employee Development", "Performance Management", "Organizational Culture"],
    ratings: 4.8,
    reviewCount: 132,
    hourlyRate: 65,
    availability: "Weekdays",
    languages: ["English", "Korean"],
    image: "https://randomuser.me/api/portraits/women/4.jpg",
    bio: "HR professional specializing in talent management and organizational development. I've helped scale startups from 10 to 500+ employees and implemented HR transformation in Fortune 100 companies.",
  }
];
  