const mentorsData = [
  {
    id: 1,
    name: "John Doe",
    title: "Senior Software Engineer",
    experience: "10+ years",
    education: "M.S. Computer Science, Stanford University",
    categories: ["Career Planning", "Skill Development", "Industry Insights"],
    expertise: ["Software Development", "AI", "Career Transitions"],
    ratings: 4.8,
    reviewCount: 127,
    hourlyRate: "$75",
    availability: "Evenings and weekends",
    languages: ["English", "Spanish"],
    image: "/mentors/mentor1.jpg",
    bio: "I've spent over a decade working at top tech companies including Google and Microsoft. My expertise lies in helping individuals transition into tech roles and advance their careers in the industry. I'm passionate about mentoring the next generation of software engineers."
  },
  {
    id: 2,
    name: "Jane Smith",
    title: "HR Director",
    experience: "15+ years",
    education: "MBA, Harvard Business School",
    categories: ["Resume Building", "Interview Preparation", "Career Planning"],
    expertise: ["HR Strategy", "Talent Acquisition", "Professional Development"],
    ratings: 4.9,
    reviewCount: 203,
    hourlyRate: "$90",
    availability: "Weekdays",
    languages: ["English", "French"],
    image: "/mentors/mentor2.jpg",
    bio: "With extensive experience in HR leadership roles at Fortune 500 companies, I specialize in helping professionals at all levels perfect their resumes, ace interviews, and develop strategic career plans. My approach combines industry best practices with personalized guidance."
  },
  {
    id: 3,
    name: "Dr. Alex Brown",
    title: "Career Counselor & Academic Advisor",
    experience: "12+ years",
    education: "Ph.D. Psychology, Columbia University",
    categories: ["Career Planning", "Graduate Studies", "Career Change"],
    expertise: ["Academic Counseling", "Career Transitions", "Personal Development"],
    ratings: 4.7,
    reviewCount: 156,
    hourlyRate: "$65",
    availability: "Flexible schedule",
    languages: ["English"],
    image: "/mentors/mentor3.jpg",
    bio: "As both a licensed psychologist and certified career counselor, I take a holistic approach to career guidance. I help clients align their professional goals with their personal values and strengths, specializing in major career transitions and academic planning."
  },
  {
    id: 4,
    name: "Maria Rodriguez",
    title: "Entrepreneurship Coach",
    experience: "8+ years",
    education: "B.S. Business Administration, UC Berkeley",
    categories: ["Entrepreneurship", "Career Change", "Networking"],
    expertise: ["Startup Advising", "Business Planning", "Venture Capital"],
    ratings: 4.9,
    reviewCount: 91,
    hourlyRate: "$85",
    availability: "Mornings and weekends",
    languages: ["English", "Spanish", "Portuguese"],
    image: "/mentors/mentor4.jpg",
    bio: "After successfully founding and exiting two tech startups, I now dedicate my time to helping aspiring entrepreneurs launch and scale their businesses. My practical approach focuses on actionable strategies for business development, fundraising, and sustainable growth."
  },
  {
    id: 5,
    name: "David Chen",
    title: "Technical Interview Coach",
    experience: "7+ years",
    education: "B.S. Computer Science, MIT",
    categories: ["Interview Preparation", "Skill Development"],
    expertise: ["Algorithm Design", "System Design", "Technical Interviews"],
    ratings: 4.8,
    reviewCount: 112,
    hourlyRate: "$95",
    availability: "Evenings and weekends",
    languages: ["English", "Mandarin"],
    image: "/mentors/mentor5.jpg",
    bio: "As a former technical interviewer at Amazon and Facebook, I've conducted over 500 technical interviews. I specialize in preparing candidates for challenging technical interviews at top tech companies, with expertise in algorithms, data structures, and system design."
  },
  {
    id: 6,
    name: "Sarah Johnson",
    title: "Remote Work Strategist",
    experience: "6+ years",
    education: "MBA, Northwestern University",
    categories: ["Remote Work", "Professional Development", "Career Change"],
    expertise: ["Remote Team Management", "Digital Collaboration", "Work-Life Balance"],
    ratings: 4.6,
    reviewCount: 78,
    hourlyRate: "$70",
    availability: "Weekdays",
    languages: ["English"],
    image: "/mentors/mentor6.jpg",
    bio: "Having led distributed teams across multiple continents, I help professionals and organizations thrive in remote work environments. I provide strategies for productivity, communication, and career advancement in the evolving landscape of remote and hybrid work."
  }
];

export default mentorsData; 